# Generated by Django 5.0.3 on 2024-03-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
